#!/bin/sh

java -ea -cp jayhorn/build/lib/jgrapht-ext-0.9.1.jar:jayhorn/build/lib/jgrapht-core-0.9.1.jar:jayhorn/build/lib/com.microsoft.z3.jar:jayhorn/build/lib/lazabs.jar:jayhorn/build/lib/princess.jar:jayhorn/build/lib/args4j-2.32.jar:jayhorn/build/lib/log4j-1.2.17.jar:jayhorn/build/lib/scala-library-2.11.7.jar:jayhorn/build/lib/scala-actors-2.11.7.jar:soottocfg/lib/soot-trunk.jar:jayhorn/build/classes/main:soottocfg/build/classes/main jayhorn.Main "$@"
