#!/bin/sh

java -cp jayhorn/lib/jgrapht-ext-0.9.1.jar:jayhorn/lib/jgrapht-core-0.9.1.jar:jayhorn/lib/com.microsoft.z3.jar:jayhorn/lib/lazabs.jar:jayhorn/lib/princess.jar:jayhorn/lib/args4j-2.0.18.jar:jayhorn/lib/log4j-1.2.8.jar:jayhorn/lib/scala-library.jar:jayhorn/lib/scala-actors-2.11.0.jar:soottocfg/lib/soot-trunk.jar:jayhorn/build/classes/main:soottocfg/build/classes/main jayhorn.Main "$@"
