package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public abstract class BasicType implements java.io.Serializable {
  public abstract <R,A> R accept(BasicType.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(soottocfg.ast.Absyn.Tint p, A arg);
    public R visit(soottocfg.ast.Absyn.Tlong p, A arg);
    public R visit(soottocfg.ast.Absyn.Tfloat p, A arg);
    public R visit(soottocfg.ast.Absyn.Tdouble p, A arg);
    public R visit(soottocfg.ast.Absyn.TVoid p, A arg);
    public R visit(soottocfg.ast.Absyn.Tboolean p, A arg);

  }

}
