package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public abstract class Body implements java.io.Serializable {
  public abstract <R,A> R accept(Body.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(soottocfg.ast.Absyn.XBody p, A arg);

  }

}
