package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class BuiltIn extends Type {
  public final BasicType basictype_;
  public BuiltIn(BasicType p1) { basictype_ = p1; }

  public <R,A> R accept(soottocfg.ast.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.BuiltIn) {
      soottocfg.ast.Absyn.BuiltIn x = (soottocfg.ast.Absyn.BuiltIn)o;
      return this.basictype_.equals(x.basictype_);
    }
    return false;
  }

  public int hashCode() {
    return this.basictype_.hashCode();
  }


}
