package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class ClassType extends Type {
  public final String ident_;
  public ClassType(String p1) { ident_ = p1; }

  public <R,A> R accept(soottocfg.ast.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.ClassType) {
      soottocfg.ast.Absyn.ClassType x = (soottocfg.ast.Absyn.ClassType)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
