package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class CNLit extends SpecExpNP {
  public final Constant constant_;
  public CNLit(Constant p1) { constant_ = p1; }

  public <R,A> R accept(soottocfg.ast.Absyn.SpecExpNP.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.CNLit) {
      soottocfg.ast.Absyn.CNLit x = (soottocfg.ast.Absyn.CNLit)o;
      return this.constant_.equals(x.constant_);
    }
    return false;
  }

  public int hashCode() {
    return this.constant_.hashCode();
  }


}
