package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class CommaExp extends CommaExpList {
  public final Exp exp_;
  public CommaExp(Exp p1) { exp_ = p1; }

  public <R,A> R accept(soottocfg.ast.Absyn.CommaExpList.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.CommaExp) {
      soottocfg.ast.Absyn.CommaExp x = (soottocfg.ast.Absyn.CommaExp)o;
      return this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return this.exp_.hashCode();
  }


}
