package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public abstract class CommaIdentList implements java.io.Serializable {
  public abstract <R,A> R accept(CommaIdentList.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(soottocfg.ast.Absyn.CommaId p, A arg);

  }

}
