package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public abstract class Constant implements java.io.Serializable {
  public abstract <R,A> R accept(Constant.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(soottocfg.ast.Absyn.Edouble p, A arg);
    public R visit(soottocfg.ast.Absyn.Eint p, A arg);
    public R visit(soottocfg.ast.Absyn.Etrue p, A arg);
    public R visit(soottocfg.ast.Absyn.Efalse p, A arg);

  }

}
