package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public abstract class DeclaratorName implements java.io.Serializable {
  public abstract <R,A> R accept(DeclaratorName.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(soottocfg.ast.Absyn.DeclName p, A arg);

  }

}
