package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public abstract class Decl implements java.io.Serializable {
  public abstract <R,A> R accept(Decl.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(soottocfg.ast.Absyn.TDecl p, A arg);
    public R visit(soottocfg.ast.Absyn.TDecl2 p, A arg);
    public R visit(soottocfg.ast.Absyn.MDecl p, A arg);

  }

}
