package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public abstract class DeclBody implements java.io.Serializable {
  public abstract <R,A> R accept(DeclBody.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(soottocfg.ast.Absyn.TDeclBody p, A arg);
    public R visit(soottocfg.ast.Absyn.TDeclBody2 p, A arg);

  }

}
