package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class Do extends IterStm {
  public final Stm stm_;
  public final Exp exp_;
  public Do(Stm p1, Exp p2) { stm_ = p1; exp_ = p2; }

  public <R,A> R accept(soottocfg.ast.Absyn.IterStm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.Do) {
      soottocfg.ast.Absyn.Do x = (soottocfg.ast.Absyn.Do)o;
      return this.stm_.equals(x.stm_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.stm_.hashCode())+this.exp_.hashCode();
  }


}
