package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class Econst extends Exp {
  public final Constant constant_;
  public Econst(Constant p1) { constant_ = p1; }

  public <R,A> R accept(soottocfg.ast.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.Econst) {
      soottocfg.ast.Absyn.Econst x = (soottocfg.ast.Absyn.Econst)o;
      return this.constant_.equals(x.constant_);
    }
    return false;
  }

  public int hashCode() {
    return this.constant_.hashCode();
  }


}
