package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class Edouble extends Constant {
  public final Double double_;
  public Edouble(Double p1) { double_ = p1; }

  public <R,A> R accept(soottocfg.ast.Absyn.Constant.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.Edouble) {
      soottocfg.ast.Absyn.Edouble x = (soottocfg.ast.Absyn.Edouble)o;
      return this.double_.equals(x.double_);
    }
    return false;
  }

  public int hashCode() {
    return this.double_.hashCode();
  }


}
