package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class Efalse extends Constant {
  public Efalse() { }

  public <R,A> R accept(soottocfg.ast.Absyn.Constant.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.Efalse) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
