package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class Epreop extends Exp {
  public final Unary_operator unary_operator_;
  public final Exp exp_;
  public Epreop(Unary_operator p1, Exp p2) { unary_operator_ = p1; exp_ = p2; }

  public <R,A> R accept(soottocfg.ast.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.Epreop) {
      soottocfg.ast.Absyn.Epreop x = (soottocfg.ast.Absyn.Epreop)o;
      return this.unary_operator_.equals(x.unary_operator_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.unary_operator_.hashCode())+this.exp_.hashCode();
  }


}
