package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class Etype extends Exp {
  public final Exp exp_;
  public final Type type_;
  public Etype(Exp p1, Type p2) { exp_ = p1; type_ = p2; }

  public <R,A> R accept(soottocfg.ast.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.Etype) {
      soottocfg.ast.Absyn.Etype x = (soottocfg.ast.Absyn.Etype)o;
      return this.exp_.equals(x.exp_) && this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.exp_.hashCode())+this.type_.hashCode();
  }


}
