package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class Evar extends Exp {
  public final String ident_;
  public Evar(String p1) { ident_ = p1; }

  public <R,A> R accept(soottocfg.ast.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.Evar) {
      soottocfg.ast.Absyn.Evar x = (soottocfg.ast.Absyn.Evar)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
