package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public abstract class Exp implements java.io.Serializable {
  public abstract <R,A> R accept(Exp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(soottocfg.ast.Absyn.Etype p, A arg);
    public R visit(soottocfg.ast.Absyn.Econdition p, A arg);
    public R visit(soottocfg.ast.Absyn.Elor p, A arg);
    public R visit(soottocfg.ast.Absyn.Eland p, A arg);
    public R visit(soottocfg.ast.Absyn.Ebitor p, A arg);
    public R visit(soottocfg.ast.Absyn.Ebitexor p, A arg);
    public R visit(soottocfg.ast.Absyn.Ebitand p, A arg);
    public R visit(soottocfg.ast.Absyn.Eeq p, A arg);
    public R visit(soottocfg.ast.Absyn.Eneq p, A arg);
    public R visit(soottocfg.ast.Absyn.Elthen p, A arg);
    public R visit(soottocfg.ast.Absyn.Egrthen p, A arg);
    public R visit(soottocfg.ast.Absyn.Ele p, A arg);
    public R visit(soottocfg.ast.Absyn.Ege p, A arg);
    public R visit(soottocfg.ast.Absyn.Eleft p, A arg);
    public R visit(soottocfg.ast.Absyn.Eright p, A arg);
    public R visit(soottocfg.ast.Absyn.Etrip p, A arg);
    public R visit(soottocfg.ast.Absyn.Eplus p, A arg);
    public R visit(soottocfg.ast.Absyn.Eminus p, A arg);
    public R visit(soottocfg.ast.Absyn.Etimes p, A arg);
    public R visit(soottocfg.ast.Absyn.Ediv p, A arg);
    public R visit(soottocfg.ast.Absyn.Emod p, A arg);
    public R visit(soottocfg.ast.Absyn.Epreop p, A arg);
    public R visit(soottocfg.ast.Absyn.Especname p, A arg);
    public R visit(soottocfg.ast.Absyn.Efld p, A arg);
    public R visit(soottocfg.ast.Absyn.Econst p, A arg);
    public R visit(soottocfg.ast.Absyn.Evar p, A arg);

  }

}
