package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class Glabel extends JumpStm {
  public final ListCommaIdentList listcommaidentlist_;
  public Glabel(ListCommaIdentList p1) { listcommaidentlist_ = p1; }

  public <R,A> R accept(soottocfg.ast.Absyn.JumpStm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.Glabel) {
      soottocfg.ast.Absyn.Glabel x = (soottocfg.ast.Absyn.Glabel)o;
      return this.listcommaidentlist_.equals(x.listcommaidentlist_);
    }
    return false;
  }

  public int hashCode() {
    return this.listcommaidentlist_.hashCode();
  }


}
