package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class Grd extends Stm {
  public final GuardStm guardstm_;
  public Grd(GuardStm p1) { guardstm_ = p1; }

  public <R,A> R accept(soottocfg.ast.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.Grd) {
      soottocfg.ast.Absyn.Grd x = (soottocfg.ast.Absyn.Grd)o;
      return this.guardstm_.equals(x.guardstm_);
    }
    return false;
  }

  public int hashCode() {
    return this.guardstm_.hashCode();
  }


}
