package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class HavocSt extends HeapStm {
  public final ListCommaIdentList listcommaidentlist_;
  public HavocSt(ListCommaIdentList p1) { listcommaidentlist_ = p1; }

  public <R,A> R accept(soottocfg.ast.Absyn.HeapStm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.HavocSt) {
      soottocfg.ast.Absyn.HavocSt x = (soottocfg.ast.Absyn.HavocSt)o;
      return this.listcommaidentlist_.equals(x.listcommaidentlist_);
    }
    return false;
  }

  public int hashCode() {
    return this.listcommaidentlist_.hashCode();
  }


}
