package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class Hps extends Stm {
  public final HeapStm heapstm_;
  public Hps(HeapStm p1) { heapstm_ = p1; }

  public <R,A> R accept(soottocfg.ast.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.Hps) {
      soottocfg.ast.Absyn.Hps x = (soottocfg.ast.Absyn.Hps)o;
      return this.heapstm_.equals(x.heapstm_);
    }
    return false;
  }

  public int hashCode() {
    return this.heapstm_.hashCode();
  }


}
