package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class If extends SelectionStm {
  public final Exp exp_;
  public final Stm stm_1, stm_2;
  public final ListElseif listelseif_;
  public If(Exp p1, Stm p2, ListElseif p3, Stm p4) { exp_ = p1; stm_1 = p2; listelseif_ = p3; stm_2 = p4; }

  public <R,A> R accept(soottocfg.ast.Absyn.SelectionStm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.If) {
      soottocfg.ast.Absyn.If x = (soottocfg.ast.Absyn.If)o;
      return this.exp_.equals(x.exp_) && this.stm_1.equals(x.stm_1) && this.listelseif_.equals(x.listelseif_) && this.stm_2.equals(x.stm_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.exp_.hashCode())+this.stm_1.hashCode())+this.listelseif_.hashCode())+this.stm_2.hashCode();
  }


}
