package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class Ifone extends SelectionStm {
  public final Exp exp_;
  public final Stm stm_;
  public final ListElseif listelseif_;
  public Ifone(Exp p1, Stm p2, ListElseif p3) { exp_ = p1; stm_ = p2; listelseif_ = p3; }

  public <R,A> R accept(soottocfg.ast.Absyn.SelectionStm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.Ifone) {
      soottocfg.ast.Absyn.Ifone x = (soottocfg.ast.Absyn.Ifone)o;
      return this.exp_.equals(x.exp_) && this.stm_.equals(x.stm_) && this.listelseif_.equals(x.listelseif_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.exp_.hashCode())+this.stm_.hashCode())+this.listelseif_.hashCode();
  }


}
