package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class Iter extends Stm {
  public final IterStm iterstm_;
  public Iter(IterStm p1) { iterstm_ = p1; }

  public <R,A> R accept(soottocfg.ast.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.Iter) {
      soottocfg.ast.Absyn.Iter x = (soottocfg.ast.Absyn.Iter)o;
      return this.iterstm_.equals(x.iterstm_);
    }
    return false;
  }

  public int hashCode() {
    return this.iterstm_.hashCode();
  }


}
