package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class JhPrg extends ProgramFile {
  public final ListDecl listdecl_;
  public JhPrg(ListDecl p1) { listdecl_ = p1; }

  public <R,A> R accept(soottocfg.ast.Absyn.ProgramFile.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.JhPrg) {
      soottocfg.ast.Absyn.JhPrg x = (soottocfg.ast.Absyn.JhPrg)o;
      return this.listdecl_.equals(x.listdecl_);
    }
    return false;
  }

  public int hashCode() {
    return this.listdecl_.hashCode();
  }


}
