package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class Logicalneg extends Unary_operator {
  public Logicalneg() { }

  public <R,A> R accept(soottocfg.ast.Absyn.Unary_operator.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.Logicalneg) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
