package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public abstract class LVarStatement implements java.io.Serializable {
  public abstract <R,A> R accept(LVarStatement.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(soottocfg.ast.Absyn.LVar p, A arg);
    public R visit(soottocfg.ast.Absyn.LVarf p, A arg);
    public R visit(soottocfg.ast.Absyn.Statem p, A arg);

  }

}
