package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class MBody extends MethodBody {
  public final Body body_;
  public MBody(Body p1) { body_ = p1; }

  public <R,A> R accept(soottocfg.ast.Absyn.MethodBody.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.MBody) {
      soottocfg.ast.Absyn.MBody x = (soottocfg.ast.Absyn.MBody)o;
      return this.body_.equals(x.body_);
    }
    return false;
  }

  public int hashCode() {
    return this.body_.hashCode();
  }


}
