package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public abstract class MethodDecl implements java.io.Serializable {
  public abstract <R,A> R accept(MethodDecl.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(soottocfg.ast.Absyn.Mth p, A arg);
    public R visit(soottocfg.ast.Absyn.Mth2 p, A arg);

  }

}
