package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public abstract class MethodBody implements java.io.Serializable {
  public abstract <R,A> R accept(MethodBody.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(soottocfg.ast.Absyn.IBody p, A arg);
    public R visit(soottocfg.ast.Absyn.MBody p, A arg);

  }

}
