package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class Mth extends MethodDecl {
  public final DeclaratorName declaratorname_;
  public final ListParameter listparameter_;
  public Mth(DeclaratorName p1, ListParameter p2) { declaratorname_ = p1; listparameter_ = p2; }

  public <R,A> R accept(soottocfg.ast.Absyn.MethodDecl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.Mth) {
      soottocfg.ast.Absyn.Mth x = (soottocfg.ast.Absyn.Mth)o;
      return this.declaratorname_.equals(x.declaratorname_) && this.listparameter_.equals(x.listparameter_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.declaratorname_.hashCode())+this.listparameter_.hashCode();
  }


}
