package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public abstract class Parameter implements java.io.Serializable {
  public abstract <R,A> R accept(Parameter.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(soottocfg.ast.Absyn.Param p, A arg);
    public R visit(soottocfg.ast.Absyn.Pfinal p, A arg);

  }

}
