package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class Pfinal extends Parameter {
  public final Type type_;
  public final DeclaratorName declaratorname_;
  public Pfinal(Type p1, DeclaratorName p2) { type_ = p1; declaratorname_ = p2; }

  public <R,A> R accept(soottocfg.ast.Absyn.Parameter.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.Pfinal) {
      soottocfg.ast.Absyn.Pfinal x = (soottocfg.ast.Absyn.Pfinal)o;
      return this.type_.equals(x.type_) && this.declaratorname_.equals(x.declaratorname_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.type_.hashCode())+this.declaratorname_.hashCode();
  }


}
