package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public abstract class ProgramFile implements java.io.Serializable {
  public abstract <R,A> R accept(ProgramFile.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(soottocfg.ast.Absyn.JhPrg p, A arg);

  }

}
