package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class PullSt extends HeapStm {
  public final ListCommaIdentList listcommaidentlist_;
  public final ListCommaExpList listcommaexplist_;
  public PullSt(ListCommaIdentList p1, ListCommaExpList p2) { listcommaidentlist_ = p1; listcommaexplist_ = p2; }

  public <R,A> R accept(soottocfg.ast.Absyn.HeapStm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.PullSt) {
      soottocfg.ast.Absyn.PullSt x = (soottocfg.ast.Absyn.PullSt)o;
      return this.listcommaidentlist_.equals(x.listcommaidentlist_) && this.listcommaexplist_.equals(x.listcommaexplist_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listcommaidentlist_.hashCode())+this.listcommaexplist_.hashCode();
  }


}
