package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class PushSt extends HeapStm {
  public final ListCommaExpList listcommaexplist_;
  public PushSt(ListCommaExpList p1) { listcommaexplist_ = p1; }

  public <R,A> R accept(soottocfg.ast.Absyn.HeapStm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.PushSt) {
      soottocfg.ast.Absyn.PushSt x = (soottocfg.ast.Absyn.PushSt)o;
      return this.listcommaexplist_.equals(x.listcommaexplist_);
    }
    return false;
  }

  public int hashCode() {
    return this.listcommaexplist_.hashCode();
  }


}
