package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public abstract class SpecExpNP implements java.io.Serializable {
  public abstract <R,A> R accept(SpecExpNP.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(soottocfg.ast.Absyn.CNLit p, A arg);
    public R visit(soottocfg.ast.Absyn.CNPfld p, A arg);

  }

}
