package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public abstract class SpecExp implements java.io.Serializable {
  public abstract <R,A> R accept(SpecExp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(soottocfg.ast.Absyn.Cep p, A arg);
    public R visit(soottocfg.ast.Absyn.Cnp p, A arg);
    public R visit(soottocfg.ast.Absyn.Cthis p, A arg);

  }

}
