package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public abstract class SpecName implements java.io.Serializable {
  public abstract <R,A> R accept(SpecName.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(soottocfg.ast.Absyn.SSnull p, A arg);

  }

}
