package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public abstract class Stm implements java.io.Serializable {
  public abstract <R,A> R accept(Stm.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(soottocfg.ast.Absyn.Lbl p, A arg);
    public R visit(soottocfg.ast.Absyn.Asg p, A arg);
    public R visit(soottocfg.ast.Absyn.NewSt p, A arg);
    public R visit(soottocfg.ast.Absyn.Cal p, A arg);
    public R visit(soottocfg.ast.Absyn.LV p, A arg);
    public R visit(soottocfg.ast.Absyn.Grd p, A arg);
    public R visit(soottocfg.ast.Absyn.Jmp p, A arg);
    public R visit(soottocfg.ast.Absyn.Iter p, A arg);
    public R visit(soottocfg.ast.Absyn.Sel p, A arg);
    public R visit(soottocfg.ast.Absyn.Hps p, A arg);

  }

}
