package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class TDecl extends Decl {
  public final String ident_;
  public final DeclBody declbody_;
  public TDecl(String p1, DeclBody p2) { ident_ = p1; declbody_ = p2; }

  public <R,A> R accept(soottocfg.ast.Absyn.Decl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.TDecl) {
      soottocfg.ast.Absyn.TDecl x = (soottocfg.ast.Absyn.TDecl)o;
      return this.ident_.equals(x.ident_) && this.declbody_.equals(x.declbody_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.declbody_.hashCode();
  }


}
