package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class TDeclBody2 extends DeclBody {
  public final ListTupleEntry listtupleentry_;
  public final ListFieldDeclaration listfielddeclaration_;
  public TDeclBody2(ListTupleEntry p1, ListFieldDeclaration p2) { listtupleentry_ = p1; listfielddeclaration_ = p2; }

  public <R,A> R accept(soottocfg.ast.Absyn.DeclBody.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.TDeclBody2) {
      soottocfg.ast.Absyn.TDeclBody2 x = (soottocfg.ast.Absyn.TDeclBody2)o;
      return this.listtupleentry_.equals(x.listtupleentry_) && this.listfielddeclaration_.equals(x.listfielddeclaration_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listtupleentry_.hashCode())+this.listfielddeclaration_.hashCode();
  }


}
