package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class TDecl2 extends Decl {
  public final String ident_1, ident_2;
  public final DeclBody declbody_;
  public TDecl2(String p1, String p2, DeclBody p3) { ident_1 = p1; ident_2 = p2; declbody_ = p3; }

  public <R,A> R accept(soottocfg.ast.Absyn.Decl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.TDecl2) {
      soottocfg.ast.Absyn.TDecl2 x = (soottocfg.ast.Absyn.TDecl2)o;
      return this.ident_1.equals(x.ident_1) && this.ident_2.equals(x.ident_2) && this.declbody_.equals(x.declbody_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ident_1.hashCode())+this.ident_2.hashCode())+this.declbody_.hashCode();
  }


}
