package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class TDeclBody extends DeclBody {
  public final ListFieldDeclaration listfielddeclaration_;
  public TDeclBody(ListFieldDeclaration p1) { listfielddeclaration_ = p1; }

  public <R,A> R accept(soottocfg.ast.Absyn.DeclBody.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.TDeclBody) {
      soottocfg.ast.Absyn.TDeclBody x = (soottocfg.ast.Absyn.TDeclBody)o;
      return this.listfielddeclaration_.equals(x.listfielddeclaration_);
    }
    return false;
  }

  public int hashCode() {
    return this.listfielddeclaration_.hashCode();
  }


}
