package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class Tfloat extends BasicType {
  public Tfloat() { }

  public <R,A> R accept(soottocfg.ast.Absyn.BasicType.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.Tfloat) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
