package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class TList2 extends TypeList {
  public final ListTypes listtypes_;
  public TList2(ListTypes p1) { listtypes_ = p1; }

  public <R,A> R accept(soottocfg.ast.Absyn.TypeList.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.TList2) {
      soottocfg.ast.Absyn.TList2 x = (soottocfg.ast.Absyn.TList2)o;
      return this.listtypes_.equals(x.listtypes_);
    }
    return false;
  }

  public int hashCode() {
    return this.listtypes_.hashCode();
  }


}
