package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public class TNames extends Types {
  public final Type type_;
  public TNames(Type p1) { type_ = p1; }

  public <R,A> R accept(soottocfg.ast.Absyn.Types.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof soottocfg.ast.Absyn.TNames) {
      soottocfg.ast.Absyn.TNames x = (soottocfg.ast.Absyn.TNames)o;
      return this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return this.type_.hashCode();
  }


}
