package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public abstract class TupleAcc implements java.io.Serializable {
  public abstract <R,A> R accept(TupleAcc.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(soottocfg.ast.Absyn.Tplvar p, A arg);

  }

}
