package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public abstract class TypeList implements java.io.Serializable {
  public abstract <R,A> R accept(TypeList.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(soottocfg.ast.Absyn.TList1 p, A arg);
    public R visit(soottocfg.ast.Absyn.TList2 p, A arg);

  }

}
