package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public abstract class Types implements java.io.Serializable {
  public abstract <R,A> R accept(Types.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(soottocfg.ast.Absyn.TNames p, A arg);

  }

}
