package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public abstract class TypeNames implements java.io.Serializable {
  public abstract <R,A> R accept(TypeNames.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(soottocfg.ast.Absyn.Types p, A arg);

  }

}
