package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public abstract class Unary_operator implements java.io.Serializable {
  public abstract <R,A> R accept(Unary_operator.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(soottocfg.ast.Absyn.Plus p, A arg);
    public R visit(soottocfg.ast.Absyn.Negative p, A arg);
    public R visit(soottocfg.ast.Absyn.Complement p, A arg);
    public R visit(soottocfg.ast.Absyn.Logicalneg p, A arg);

  }

}
