package soottocfg.ast.Absyn; // Java Package generated by the BNF Converter.

public abstract class VarDecl implements java.io.Serializable {
  public abstract <R,A> R accept(VarDecl.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(soottocfg.ast.Absyn.VDecl p, A arg);

  }

}
