package soottocfg.randoop;

/**
 * @author Huascar Sanchez
 */
public interface UnitTest {
  /**
   * Runs a test generated by {@link Randoop}.
   *
   * @throws Throwable if an unexpected error occurs
   */
  void run() throws Throwable;

  // explicitly indicating that implementors must
  // override this method.
  @Override String toString();
}
